name   = "Solarized Dark"
author = "Ethan Schoonover"
dark   = true

[palette]
background = "#002b36"
surface    = "#073642"
overlay    = "#586e75"

text    = "#839496"
subtext = "#93a1a1"
muted   = "#657b83"

accent     = "#268bd2"
green      = "#859900"
yellow     = "#b58900"
red        = "#dc322f"
blue       = "#268bd2"
purple     = "#6c71c4"
cyan       = "#2aa198"

border     = "#073642"
selection  = "#073642"
cursor     = "#839496"
